printer/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import (
    ControlPrinterAPIView,
    ThreeDPrinterListCreateView,
    printer_info,
    delete_printer,
    web,
    select_printer,
    send_command,
    control_printer,
    add_printer,
    print_gcode,
    success_printer,
    orders_view,
    admin_select_printer,
    admin_add_3d_printer,
    admin_print_gcode,
    success_print,
    update_order,
    print_order,
    kab_print,
    add_3d_printerUser,
    telegram_auth,
    upload_file_view, printer_action, printers_user, orders_user, printing, management, add_3d_model, submit_model,
    choose_printer, order_detail, contact, update_order_view, profile_view, chat_view, send_message,
    get_messages, view_gcode, send_to_printer
)

app_name = 'printer'

urlpatterns = [
    path('control_printer/', ControlPrinterAPIView.as_view(), name='control-printer-api'),
    path('printers/', ThreeDPrinterListCreateView.as_view(), name='printer-list-create'),
    path('select_printer/', select_printer, name='select_printer'),
    path('send_command/<int:printer_id>/', send_command, name='send-command'),
    path('printer_info/<int:printer_id>/', printer_info, name='printer_info'),
    path('control_printer/', control_printer, name='control_printer'),
    path('add_printer/', add_printer, name='add_printer'),
    path('print_gcode/', print_gcode, name='print_gcode'),
    path("success_printer/", success_printer, name='success_printer'),
    path('delete-printer/<int:printer_id>/', delete_printer, name='delete_printer'),
    path('web/', web, name='web'),
    path('orders/', orders_view, name='orders'),
    path('select_printer/', admin_select_printer, name='admin_select_printer'),
    path('add_3d_printer/', admin_add_3d_printer, name='admin_add_3d_printer'),
    path('print_gcode/', admin_print_gcode, name='admin_print_gcode'),
    path('success_print/', success_print, name='success_print'),
    path('update_order/', update_order, name='update_order'),
    path('print-order/', print_order, name='print_order'),
    path('add_3d_printer/', add_3d_printerUser, name='add_3d_printer'),
    path('kab_print', kab_print, name='kab_print'),
    path('telegram-auth/', telegram_auth, name='telegram_auth'),
    path('upload/', upload_file_view, name='upload_file'),
    path('printer_action/', printer_action, name='printer_action'),
    path('printers_user/', printers_user, name='printers_user'),
    path('orders_user/', orders_user, name='orders_user'),
    path('management/', management, name='management'),
    path('printing/', printing, name='printing'),
    path('api/choose_printer/<int:printer_id>/', choose_printer, name='choose_printer'),
    path('api/add_model/<int:printer_id>/', add_3d_model, name='add_3d_model'),
    path('api/order_detail/<int:order_id>/', order_detail, name='order_detail'),
    path('submit_model/', submit_model, name='submit_model'),
    path('contact/', contact, name='contact'),
    path('update_order/<int:order_id>/', update_order_view, name='update_order'),
    path('profile/', profile_view, name='profile'),
    path('chat/', chat_view, name='chat'),
    path('chat/send_message/<int:dialog_id>/', send_message, name='send_message'),
    path('add/<int:printer_id>/', add_3d_model, name='add_3d_model'),
    path('order/<int:order_id>/', order_detail, name='order_detail'),
    path('view_gcode/<int:pk>/', view_gcode, name='view_gcode'),
    path('upload/<int:printer_id>/', add_3d_model, name='add_3d_model'),
    path('order/<int:order_id>/', order_detail, name='order_detail'),
    path('gcode/<int:order_id>/', view_gcode, name='view_gcode'),
    path('send_to_printer/<int:order_id>/', send_to_printer, name='send_to_printer'),
    path('chat/', chat_view, name='chat'),
    path('get_messages/<int:dialog_id>/', get_messages, name='get_messages'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

printerapp/urls.py
from django.contrib import admin
from django.urls import path, include
from printer import views
from printer.urls import urlpatterns as api_urls

urlpatterns = [
    path("", views.web, name='web'),
    path('api/', include(api_urls)),
    path('admin/', admin.site.urls),
    path("", include("printer.urls")),
    path('users/', include('users.urls', namespace="users")),
    # path('select_printer/', views.select_printer, name='select-printer'),
    # path('send_command/<int:printer_id>/', views.send_command, name='send-command'),
    # path('printer_info/<int:printer_id>/', views.printer_info, name='printer-info'),

    path("control_printer/", views.control_printer, name='control_printer'),
    # path("add_3d_printer/", views.add_3d_printer, name='add_3d_printer'),
    # path("success_printer/", views.success_printer, name='success_printer'),
    path('web/', views.home, name='home'),




]

users/urls.py
from django.urls import path
from . import views
from .views import register, admin_select_printer, admin_add_3d_printer, admin_print_gcode

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout'),
    path('home/', views.home, name='home'),
    path('register/', register, name='register'),
    path('select_printer/', admin_select_printer, name='admin_select_printer'),
    path('add_3d_printer/', admin_add_3d_printer, name='admin_add_3d_printer'),
    path('print_gcode/', admin_print_gcode, name='admin_print_gcode'),
]

printer/views.py
import serial
import logging
import requests

from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse, path
from django.views.decorators.csrf import csrf_exempt
from rest_framework import generics, status
from rest_framework.views import APIView
from rest_framework.response import Response

from .serializers import ThreeDPrinterSerializer, CommandSerializer, MessageSerializer
from .forms import (
    ThreeDPrinterForm, PrinterSelectForm, GCodeForm, ThreeDPrinterFormUser, ModelUploadForm, ContactForm,
    UserProfileForm, CustomPasswordChangeForm, PrivateMessageForm
)
from .models import (
    ThreeDPrinter, Job, Command, ThermalData, GCodeFile, Order, ThreeDPrinterUser, UserProfile,
    Dialog, PrivateMessage
)
from users.views import person_required, admin_required



logger = logging.getLogger(__name__)

@login_required
def admin_select_printer(request):
    if request.user.is_staff:
        return render(request, 'printerapp/select_printer.html')
    else:
        return redirect('add_printer')

def printers_view(request):
    printer_users = ThreeDPrinterUser.objects.all()
    return render(request, 'kab_print.html', {'printer_users': printer_users})

@login_required
def admin_add_3d_printer(request):
    if request.user.is_staff:
        return render(request, 'printerapp/add_3d_printer.html')
    else:
        return redirect('print_gcode')

@login_required
def admin_print_gcode(request):
    if request.user.is_staff:
        return render(request, 'printerapp/print_gcode.html')
    else:
        return redirect('print_gcode')

@login_required
def add_printer(request):
    if not request.user.is_staff:
        return render(request, 'add_printer.html')
    else:
        return redirect('select_printer')

@login_required
def print_gcode(request):
    if not request.user.is_staff:
        if request.method == 'POST':
            form = GCodeForm(request.POST, request.FILES)
            if form.is_valid():
                gcode_file = form.save()
                order = Order.objects.create(user=request.user, model_file=gcode_file.file)
                try:
                    com_port = "COM5"
                    baud_rate = 115200
                    with serial.Serial(port=com_port, baudrate=baud_rate, timeout=1) as ser, open(gcode_file.file.path, 'rb') as file:
                        data = file.read()
                        ser.write(data)
                    return redirect('success_print')
                except Exception as e:
                    logger.error(f"Error sending G-code to printer: {e}")
                    return render(request, 'print_gcode.html', {'form': form, 'error': str(e)})
        else:
            form = GCodeForm()
        return render(request, 'print_gcode.html', {'form': form})
    else:
        return redirect('admin_print_gcode')

@admin_required
def orders_view(request):
    orders = Order.objects.all()
    filters = {k: v for k, v in request.GET.items() if v}

    if 'order_id' in filters:
        orders = orders.filter(id=filters['order_id'])
    if 'upload_date' in filters:
        orders = orders.filter(upload_date=filters['upload_date'])
    if 'username' in filters:
        orders = orders.filter(user__username=filters['username'])
    if 'status' in filters:
        orders = orders.filter(status=filters['status'])

    context = {'orders': orders}
    return render(request, 'orders.html', context)

def update_order_view(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        order.price = request.POST.get('price')
        order.status = request.POST.get('status')
        order.save()
        return redirect(reverse('orders'))

def web(request):
    return render(request, "web.html")

@admin_required
def control_printer(request):
    if request.method == 'POST':
        command = request.POST.get('command')
        if command:
            try:
                with serial.Serial('COM5', 115200) as ser:
                    commands = {
                        "G28": "G28\n",
                        "Сдвиг каретки на 10мм влево по X": "G91\nG1 X-10 F3000\n",
                        "Сдвиг каретки на 10мм вправо по X": "G91\nG1 X10 F3000\n",
                        "Остановить выполнение текущей задачи": "M84\n",
                        "Сдвиг стола на 10мм влево по Y": "G91\nG1 Y-10 F3000\n",
                        "Сдвиг стола на 10мм вправо по Y": "G91\nG1 Y10 F3000\n",
                        "Сдвиг подъема оси на 10мм влево по Z": "G91\nG1 Z-10 F3000\n",
                        "Сдвиг подъема оси на 10мм вправо по Z": "G91\nG1 Z10 F3000\n"
                    }
                    if command in commands:
                        ser.write(commands[command].encode())
                    return HttpResponse(f"Команда '{command}' успешно отправлена на принтер.")
            except serial.SerialException as e:
                logger.error(f"Error controlling printer: {e}")
                return HttpResponse(f"Ошибка: {e}")
    return render(request, 'control_printer.html')

@login_required
def add_3d_printer(request):
    if request.method == 'POST':
        form = ThreeDPrinterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('success_printer')
    else:
        form = ThreeDPrinterForm()
    return render(request, 'add_printer.html', {'form': form})

@login_required
def success_printer(request):
    return render(request, 'success_printer.html')

@login_required
def success_print(request):
    return render(request, 'success_print.html')

@login_required
def kab_print(request):
    return render(request, 'kab_print.html')

class ThreeDPrinterListCreateView(generics.ListCreateAPIView):
    queryset = ThreeDPrinter.objects.all()
    serializer_class = ThreeDPrinterSerializer

class ControlPrinterAPIView(APIView):
    def post(self, request, *args, **kwargs):
        command_text = request.data.get('command')
        if command_text:
            try:
                with serial.Serial('COM5', 115200) as ser:
                    commands = {
                        "G28": "G28\n",
                        "Сдвиг каретки на 10мм влево по X": "G91\nG1 X-10 F3000\n",
                        "Сдвиг каретки на 10мм вправо по X": "G91\nG1 X10 F3000\n",
                        "Остановить выполнение текущей задачи": "M112\n",
                        "Сдвиг стола на 10мм влево по Y": "G91\nG1 Y-10 F3000\n",
                        "Сдвиг стола на 10мм вправо по Y": "G91\nG1 Y10 F3000\n",
                        "Сдвиг подъема оси на 10мм влево по Z": "G91\nG1 Z-10 F3000\n",
                        "Сдвиг подъема оси на 10мм вправо по Z": "G91\nG1 Z10 F3000\n"
                    }
                    if command_text in commands:
                        ser.write(commands[command_text].encode())
                    return Response({"message": f"Команда '{command_text}' успешно отправлена на принтер."}, status=status.HTTP_200_OK)
            except serial.SerialException as e:
                logger.error(f"Error controlling printer: {e}")
                return Response({"error": f"Ошибка: {e}"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        return Response({"error": "Не указана команда"}, status=status.HTTP_400_BAD_REQUEST)

@admin_required
def select_printer(request):
    printers = ThreeDPrinterUser.objects.all()
    if request.method == 'POST':
        printer_id = request.POST.get('printer_id')
        printer = get_object_or_404(ThreeDPrinterUser, id=printer_id)
        printer.delete()
        return redirect('printers_list')
    return render(request, 'select_printer.html', {'printers': printers})

@admin_required
def send_command(request, printer_id):
    selected_printer = get_object_or_404(ThreeDPrinter, id=printer_id)
    if request.method == 'POST':
        command = request.POST.get('command')
        try:
            with serial.Serial(selected_printer.com_port, 115200, timeout=1) as ser:
                ser.write(command.encode())
                return HttpResponse(f"Command '{command}' sent to printer {selected_printer.name}.")
        except serial.SerialException as e:
            logger.error(f"Error sending command to printer: {e}")
            return HttpResponse(f"Error: {e}")
    return render(request, 'send_command.html', {'selected_printer': selected_printer})

@admin_required
def printer_info(request, printer_id):
    selected_printer = get_object_or_404(ThreeDPrinter, id=printer_id)
    return render(request, 'printer_info.html', {'selected_printer': selected_printer})

@admin_required
def delete_printer(request, printer_id):
    try:
        printer = get_object_or_404(ThreeDPrinter, pk=printer_id)
        printer.delete()
        return redirect('select_printer')
    except ThreeDPrinter.DoesNotExist:
        return render(request, 'select_printer.html', {'printer_id': printer_id})

def home(request):
    return render(request, 'web.html')

def print_order(request):
    if request.method == 'POST':
        order_id = request.POST.get('order_id')
        success = True
        return JsonResponse({'success': success})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method'})

@login_required
def update_order(request, order_id):
    if request.method == 'POST':
        price = request.POST.get('price')
        status = request.POST.get('status')
        order = get_object_or_404(Order, pk=order_id)

printer/templates/kab_print/chat.html
{% load static %}
{% include 'header.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chat Page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/print.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/chat.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
</head>
<body>
<div class="wrapper">
    <div class="sidebar">
        <div class="tab">
            <a href="{% url 'printers_user' %}" class="tablinks">Принтеры</a>
            <a href="{% url 'orders_user' %}" class="tablinks">Заказы</a>
            <a href="{% url 'management' %}" class="tablinks">Управление</a>
            <a href="{% url 'printing' %}" class="tablinks">Инструкция</a>
            <a href="{% url 'chat' %}" class="tablinks">Чаты</a>
        </div>
    </div>

    <div class="content">
        <div id="dialogs">
            <h2>Чаты</h2>

            <ul>
                {% for dialog, username in dialogs %}
                    <li>
                        <a href="#" class="dialog-link" data-userName="{{ username }}"  data-id="{{ dialog.id }}">
                            {{ username }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>

        <div id="chat">
            <h2 id="ChatWhit">Чат</h2>
            <div id="messages"></div>
            <form id="messageForm" method="post" action="send_message">
                {% csrf_token %}
                <textarea name="message" id="message" rows="3"></textarea>
                <input hidden id="Dialog_id" name=Dialog_id" value="{{ dialog.id }}">
                <button type="submit">Отправить</button>
            </form>
        </div>
        <script>
            var currentDialogId = null;
            $(document).ready(function() {
                function loadMessages(dialogId) {
                    $.get("{% url 'get_messages' 0 %}".replace('0', dialogId), function(data) {
                        var messagesDiv = $('#messages');
                        messagesDiv.empty();
                        data.messages.forEach(function(message) {
                            var msg = `<div><strong>${message.sender}:</strong> ${message.message} <small>${message.timestamp}</small></div>`;

                            messagesDiv.append(msg);
                        });
                    }).fail(function(){
                        alert("Failed to load messages");
                        console.error("Error loading messages");
                    });
                }

                $('.dialog-link').click(function(e) {
                    e.preventDefault();
                    var dialogId = $(this).data('id');
                    currentDialogId = dialogId;

                    let LabelChat = $('#ChatWhit');
                    let username = $(this).data('username');
                    LabelChat.html(`Чат с ${username}`)

                    loadMessages(dialogId);
                    $('#messageForm').attr('action', "{% url 'send_message' 0 %}".replace('0', dialogId));
                    clearInterval(window.messageInterval);
                    window.messageInterval = setInterval(function() {
                        loadMessages(dialogId);
                    }, 5000);
                });

                $('#messageForm').submit(function (e) {
                    e.preventDefault();
                    let form = $(this);
                    $.ajax({
                        type: 'POST',
                        url: form.attr('action'),
                        data: form.serialize(),
                        success: function (data) {
                            if (data.status === 'success') {
                                loadMessages(currentDialogId);
                                form[0].reset();
                            } else {
                                console.error("Ошибка в отправке:", data.errors);
                            }
                        },
                        error: function () {
                            // Обработка ошибки
                            alert("Ошибка в отправке");
                            console.error("Ошибка в отправке");
                        }
                    });
                });
            });

            function ShowUsers()
            {

            }

        </script>
    </div>
</div>
</body>
</html>

printer/templates/kab_print/dialog.html
<!DOCTYPE html>
<html>
<head>
    <title>Dialog</title>
</head>
<body>
    <h1>Dialog with {{ recipient.username }}</h1>
    <div id="chat-box">
        {% for message in messages %}
            <p><strong>{{ message.sender.username }}:</strong> {{ message.message }}</p>
        {% endfor %}
    </div>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send</button>
    </form>
    <a href="{% url 'chat' %}">Back to chat list</a>
</body>
</html>

printer/templates/kab_print/inbox.html
<!DOCTYPE html>
<html>
<head>
    <title>Inbox</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h2>Inbox</h2>
        <ul>
            {% for message in messages %}
                <li>
                    <strong>From {{ message.sender.username }}:</strong> {{ message.message }} <br>
                    <small>{{ message.timestamp }}</small>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

printer/templates/kab_print/management.html
{% load static %}

{% include 'header.html' %}
<div class="wrapper">
    <div class="sidebar">
        <div class="tab">
            <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Страница с вкладками</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/print.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
            <a href="{% url 'printers_user' %}" class="tablinks">Принтеры</a>
            <a href="{% url 'orders_user' %}" class="tablinks">Заказы</a>
            <a href="{% url 'management' %}" class="tablinks">Управление</a>
            <a href="{% url 'printing' %}" class="tablinks">Инструкция</a>
            <a href="{% url 'chat' %}" class="tablinks">Чаты</a>
        </div>
    </div>
<div class="content">
        {% block content %}
        <div id="Printers">
            <h3>Программа для управления</h3>
     <p>Для того чтобы добавить свой принтер на сайт, вам нужно скачать программу, установить и войти в систему под своими учетными данными. Подключить принтер к компьютеру через шнур.</p>
                <p>Подключите принтер к компьютеру через COM-порт, чтобы программа смогла его обнаружить и добавить на сайт.</p>
                <button class="btn" onclick="window.location.href='~/static/fails/OneFile.zip'">Скачать программу</button>
</div>
    {% endblock %}

printer/templates/kab_print/orders_user.html
{% load static %}
{% include 'header.html' %}
<link rel="stylesheet" type="text/css" href="{% static 'css/print.css' %}">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">

<div class="wrapper">
    <div class="sidebar">
        <div class="tab">
            <a href="{% url 'printers_user' %}" class="tablinks">Принтеры</a>
            <a href="{% url 'orders_user' %}" class="tablinks">Заказы</a>
            <a href="{% url 'management' %}" class="tablinks">Управление</a>
            <a href="{% url 'printing' %}" class="tablinks">Инструкция</a>
            <a href="{% url 'chat' %}" class="tablinks">Чаты</a>
        </div>
    </div>
    <div class="content">
        {% block content %}
        <div id="Orders_user">
            <h3>Заказы</h3>
            <table id="ordersTable" class="display">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Дата загрузки</th>
                        <th>Цена</th>
                        <th>Кто печатал</th>
                        <th>Статус</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                    <tr>
                        <td>{{ order.id }}</td>
                        <td>{{ order.upload_date }}</td>
                        <td>{{ order.price }}</td>
                        <td>{{ order.customer }}</td>

                        <td>{{ order.status }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endblock %}
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
<script>
    $(document).ready(function(){
        $('#ordersTable').DataTable();
    });
</script>

printer/templates/kab_print/printers_user.html
{% load static %}

{% include 'header.html' %}

<!-- Подключение DataTables JS и CSS -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
<script src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>

<div class="wrapper">
    <div class="sidebar">
        <div class="tab">
            <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Страница с вкладками</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/print.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
            <a href="{% url 'printers_user' %}" class="tablinks">Принтеры</a>
            <a href="{% url 'orders_user' %}" class="tablinks">Заказы</a>
            <a href="{% url 'management' %}" class="tablinks">Управление</a>
            <a href="{% url 'printing' %}" class="tablinks">Инструкция</a>
            <a href="{% url 'chat' %}" class="tablinks">Чаты</a>
        </div>
    </div>
    <div class="content">
        {% block content %}
        <div id="Printers">
            <h3>Принтеры</h3>

            <h4>Принтеры пользователя</h4>
            <table id="userPrintersTable" class="display">
                <thead>
                    <tr>
                        <th>Бренд</th>
                        <th>Модель</th>
                        <th>Размеры</th>
                        <th>Город</th>
                        <th>Статус</th>
                    </tr>
                </thead>
                <tbody>
                    {% for printer in user_printers %}
                    <tr class="printerRow" data-url="https://{{  printer.ip_address }}">
                        <td>{{ printer.brand }}</td>
                        <td>{{ printer.model }}</td>
                        <td>{{ printer.build_volume }}</td>
                        <td>{{ printer.city }}</td>
                        <td class="status">{{ printer.status }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <h4>Доступные принтеры для печати</h4>
            <table id="allPrintersTable" class="display">
                <thead>
                    <tr>
                        <th>Бренд</th>
                        <th>Модель</th>
                        <th>Размеры</th>
                        <th>Город</th>
                        <th>Статус</th>
                        <th>Печать</th>
                    </tr>
                </thead>
                <tbody>
                    {% for printer in all_printers %}
                    <tr class="printerRow" data-url="https://{{  printer.ip_address }}">
                        <td>{{ printer.brand }}</td>
                        <td>{{ printer.model }}</td>
                        <td>{{ printer.build_volume }}</td>
                        <td>{{ printer.city }}</td>
                        <td class="status">{{ printer.status }}</td>
                        <td>
                            <form action="{% url 'choose_printer' printer.id %}" method="post">
                                {% csrf_token %}
                                <input type="hidden" name="com_port" value="{{ printer.com_port }}">
                                <input type="hidden" name="ip_address" value="{{ printer.ip_address }}">
                                <button type="submit" class="btn btn-primary">Выбрать</button>
                            </form>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% endblock %}
    </div>
</div>



<script>
$(document).ready(function () {
    $('#userPrintersTable').DataTable();
    $('#allPrintersTable').DataTable();

    let timerId = setInterval(() => {
        $('.printerRow').each(function (index) {
            let url = $(this).data('url')
            let row = this;
            fetch(url, {
                method: 'HEAD'
            }).then(response => {
                if (response.ok) {
                    $(row).children('.status').html('Ожидает')
                } else {
                    $(row).children('.status').html('Недоступен')
                }
            }).catch(error => {
                $(row).children('.status').html('Недоступен')
                console.error('Произошла ошибка при проверке доступности адреса:', error);
            });
        })
    }, 20);


});
</script>

printer/templates/kab_print/printing.html
{% load static %}
{% include 'header.html' %}
{% block content %}
<div class="wrapper">
    <div class="sidebar">
        <div class="tab">
            <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Страница с вкладками</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/print.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
            <a href="{% url 'printers_user' %}" class="tablinks">Принтеры</a>
            <a href="{% url 'orders_user' %}" class="tablinks">Заказы</a>
            <a href="{% url 'management' %}" class="tablinks">Управление</a>
            <a href="{% url 'printing' %}" class="tablinks">Инструкция</a>
            <a href="{% url 'chat' %}" class="tablinks">Чаты</a>
        </div>
    </div>
<div id="Printing">
    <h3>Инструкция по установке</h3>

</div>
{% endblock %}

printer/templates/kab_print/profile.html
{% load static %}

{% include 'header.html' %}
<html>
<head>
    <title>Profile</title>
</head>
<body>
    <h1>Profile</h1>
    <form method="post">
        {% csrf_token %}
        {{ profile_form.as_p }}
        {{ password_form.as_p }}
        <button type="submit">Save changes</button>
    </form>
    <p>Rating: {{ rating }}</p>
</body>
</html>

printer/templates/kab_print/user_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Users List</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h2>Users List</h2>
        <ul>
            {% for user in users %}
                <li>
                    <a href="{% url 'printer:send_message' user.id %}">{{ user.username }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>