printer/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from .views import (
    ControlPrinterAPIView,
    ThreeDPrinterListCreateView,
    printer_info,
    delete_printer,
    web,
    select_printer,
    send_command,
    control_printer,
    add_printer,
    print_gcode,
    success_printer,
    orders_view,
    admin_select_printer,
    admin_add_3d_printer,
    admin_print_gcode,
    success_print,
    update_order,
    print_order,
    kab_print,
    add_3d_printerUser,
    telegram_auth,
    upload_file_view, printer_action, printers_user, orders_user, printing, management, add_3d_model, submit_model,
    choose_printer, order_detail, contact, update_order_view, profile_view, chat_view, send_message,
    get_messages, view_gcode, send_to_printer
)

app_name = 'printer'

urlpatterns = [
    path('control_printer/', ControlPrinterAPIView.as_view(), name='control-printer-api'),
    path('printers/', ThreeDPrinterListCreateView.as_view(), name='printer-list-create'),
    path('select_printer/', select_printer, name='select_printer'),
    path('send_command/<int:printer_id>/', send_command, name='send-command'),
    path('printer_info/<int:printer_id>/', printer_info, name='printer_info'),
    path('control_printer/', control_printer, name='control_printer'),
    path('add_printer/', add_printer, name='add_printer'),
    path('print_gcode/', print_gcode, name='print_gcode'),
    path("success_printer/", success_printer, name='success_printer'),
    path('delete-printer/<int:printer_id>/', delete_printer, name='delete_printer'),
    path('web/', web, name='web'),
    path('orders/', orders_view, name='orders'),
    path('select_printer/', admin_select_printer, name='admin_select_printer'),
    path('add_3d_printer/', admin_add_3d_printer, name='admin_add_3d_printer'),
    path('print_gcode/', admin_print_gcode, name='admin_print_gcode'),
    path('success_print/', success_print, name='success_print'),
    path('update_order/', update_order, name='update_order'),
    path('print-order/', print_order, name='print_order'),
    path('add_3d_printer/', add_3d_printerUser, name='add_3d_printer'),
    path('kab_print', kab_print, name='kab_print'),
    path('telegram-auth/', telegram_auth, name='telegram_auth'),
    path('upload/', upload_file_view, name='upload_file'),
    path('printer_action/', printer_action, name='printer_action'),
    path('printers_user/', printers_user, name='printers_user'),
    path('orders_user/', orders_user, name='orders_user'),
    path('management/', management, name='management'),
    path('printing/', printing, name='printing'),
    path('api/choose_printer/<int:printer_id>/', choose_printer, name='choose_printer'),
    path('api/add_model/<int:printer_id>/', add_3d_model, name='add_3d_model'),
    path('api/order_detail/<int:order_id>/', order_detail, name='order_detail'),
    path('submit_model/', submit_model, name='submit_model'),
    path('contact/', contact, name='contact'),
    path('update_order/<int:order_id>/', update_order_view, name='update_order'),
    path('profile/', profile_view, name='profile'),
    path('chat/', chat_view, name='chat'),
    path('chat/send_message/<int:dialog_id>/', send_message, name='send_message'),
    path('add/<int:printer_id>/', add_3d_model, name='add_3d_model'),
    path('order/<int:order_id>/', order_detail, name='order_detail'),
    path('view_gcode/<int:pk>/', view_gcode, name='view_gcode'),
    path('upload/<int:printer_id>/', add_3d_model, name='add_3d_model'),
    path('order/<int:order_id>/', order_detail, name='order_detail'),
    path('gcode/<int:order_id>/', view_gcode, name='view_gcode'),
    path('send_to_printer/<int:order_id>/', send_to_printer, name='send_to_printer'),
    path('chat/', chat_view, name='chat'),
    path('get_messages/<int:dialog_id>/', get_messages, name='get_messages'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

printerapp/urls.py
from django.contrib import admin
from django.urls import path, include
from printer import views
from printer.urls import urlpatterns as api_urls

urlpatterns = [
    path("", views.web, name='web'),
    path('api/', include(api_urls)),
    path('admin/', admin.site.urls),
    path("", include("printer.urls")),
    path('users/', include('users.urls', namespace="users")),
    # path('select_printer/', views.select_printer, name='select-printer'),
    # path('send_command/<int:printer_id>/', views.send_command, name='send-command'),
    # path('printer_info/<int:printer_id>/', views.printer_info, name='printer-info'),

    path("control_printer/", views.control_printer, name='control_printer'),
    # path("add_3d_printer/", views.add_3d_printer, name='add_3d_printer'),
    # path("success_printer/", views.success_printer, name='success_printer'),
    path('web/', views.home, name='home'),




]

users/urls.py
from django.urls import path
from . import views
from .views import register, admin_select_printer, admin_add_3d_printer, admin_print_gcode

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout'),
    path('home/', views.home, name='home'),
    path('register/', register, name='register'),
    path('select_printer/', admin_select_printer, name='admin_select_printer'),
    path('add_3d_printer/', admin_add_3d_printer, name='admin_add_3d_printer'),
    path('print_gcode/', admin_print_gcode, name='admin_print_gcode'),
]

printer/views.py
import serial
import logging
import requests

from django.core.files.storage import FileSystemStorage
from django.core.mail import send_mail
from django.contrib.auth import authenticate, login, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse, path
from django.views.decorators.csrf import csrf_exempt
from rest_framework import generics, status
from rest_framework.views import APIView
from rest_framework.response import Response

from .serializers import ThreeDPrinterSerializer, CommandSerializer, MessageSerializer
from .forms import (
    ThreeDPrinterForm, PrinterSelectForm, GCodeForm, ThreeDPrinterFormUser, ModelUploadForm, ContactForm,
    UserProfileForm, CustomPasswordChangeForm, PrivateMessageForm
)
from .models import (
    ThreeDPrinter, Job, Command, ThermalData, GCodeFile, Order, ThreeDPrinterUser, UserProfile,
    Dialog, PrivateMessage
)
from users.views import person_required, admin_required



logger = logging.getLogger(__name__)

@login_required
def admin_select_printer(request):
    if request.user.is_staff:
        return render(request, 'printerapp/select_printer.html')
    else:
        return redirect('add_printer')

def printers_view(request):
    printer_users = ThreeDPrinterUser.objects.all()
    return render(request, 'kab_print.html', {'printer_users': printer_users})

@login_required
def admin_add_3d_printer(request):
    if request.user.is_staff:
        return render(request, 'printerapp/add_3d_printer.html')
    else:
        return redirect('print_gcode')

@login_required
def admin_print_gcode(request):
    if request.user.is_staff:
        return render(request, 'printerapp/print_gcode.html')
    else:
        return redirect('print_gcode')

@login_required
def add_printer(request):
    if not request.user.is_staff:
        return render(request, 'add_printer.html')
    else:
        return redirect('select_printer')

@login_required
def print_gcode(request):
    if not request.user.is_staff:
        if request.method == 'POST':
            form = GCodeForm(request.POST, request.FILES)
            if form.is_valid():
                gcode_file = form.save()
                order = Order.objects.create(user=request.user, model_file=gcode_file.file)
                try:
                    com_port = "COM5"
                    baud_rate = 115200
                    with serial.Serial(port=com_port, baudrate=baud_rate, timeout=1) as ser, open(gcode_file.file.path, 'rb') as file:
                        data = file.read()
                        ser.write(data)
                    return redirect('success_print')
                except Exception as e:
                    logger.error(f"Error sending G-code to printer: {e}")
                    return render(request, 'print_gcode.html', {'form': form, 'error': str(e)})
        else:
            form = GCodeForm()
        return render(request, 'print_gcode.html', {'form': form})
    else:
        return redirect('admin_print_gcode')

@admin_required
def orders_view(request):
    orders = Order.objects.all()
    filters = {k: v for k, v in request.GET.items() if v}

    if 'order_id' in filters:
        orders = orders.filter(id=filters['order_id'])
    if 'upload_date' in filters:
        orders = orders.filter(upload_date=filters['upload_date'])
    if 'username' in filters:
        orders = orders.filter(user__username=filters['username'])
    if 'status' in filters:
        orders = orders.filter(status=filters['status'])

    context = {'orders': orders}
    return render(request, 'orders.html', context)

def update_order_view(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    if request.method == 'POST':
        order.price = request.POST.get('price')
        order.status = request.POST.get('status')
        order.save()
        return redirect(reverse('orders'))

def web(request):
    return render(request, "web.html")

@admin_required
def control_printer(request):
    if request.method == 'POST':
        command = request.POST.get('command')
        if command:
            try:
                with serial.Serial('COM5', 115200) as ser:
                    commands = {
                        "G28": "G28\n",
                        "Сдвиг каретки на 10мм влево по X": "G91\nG1 X-10 F3000\n",
                        "Сдвиг каретки на 10мм вправо по X": "G91\nG1 X10 F3000\n",
                        "Остановить выполнение текущей задачи": "M84\n",
                        "Сдвиг стола на 10мм влево по Y": "G91\nG1 Y-10 F3000\n",
                        "Сдвиг стола на 10мм вправо по Y": "G91\nG1 Y10 F3000\n",
                        "Сдвиг подъема оси на 10мм влево по Z": "G91\nG1 Z-10 F3000\n",
                        "Сдвиг подъема оси на 10мм вправо по Z": "G91\nG1 Z10 F3000\n"
                    }
                    if command in commands:
                        ser.write(commands[command].encode())
                    return HttpResponse(f"Команда '{command}' успешно отправлена на принтер.")
            except serial.SerialException as e:
                logger.error(f"Error controlling printer: {e}")
                return HttpResponse(f"Ошибка: {e}")
    return render(request, 'control_printer.html')

@login_required
def add_3d_printer(request):
    if request.method == 'POST':
        form = ThreeDPrinterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('success_printer')
    else:
        form = ThreeDPrinterForm()
    return render(request, 'add_printer.html', {'form': form})

@login_required
def success_printer(request):
    return render(request, 'success_printer.html')

@login_required
def success_print(request):
    return render(request, 'success_print.html')

@login_required
def kab_print(request):
    return render(request, 'kab_print.html')

class ThreeDPrinterListCreateView(generics.ListCreateAPIView):
    queryset = ThreeDPrinter.objects.all()
    serializer_class = ThreeDPrinterSerializer

class ControlPrinterAPIView(APIView):
    def post(self, request, *args, **kwargs):
        command_text = request.data.get('command')
        if command_text:
            try:
                with serial.Serial('COM5', 115200) as ser:
                    commands = {
                        "G28": "G28\n",
                        "Сдвиг каретки на 10мм влево по X": "G91\nG1 X-10 F3000\n",
                        "Сдвиг каретки на 10мм вправо по X": "G91\nG1 X10 F3000\n",
                        "Остановить выполнение текущей задачи": "M112\n",
                        "Сдвиг стола на 10мм влево по Y": "G91\nG1 Y-10 F3000\n",
                        "Сдвиг стола на 10мм вправо по Y": "G91\nG1 Y10 F3000\n",
                        "Сдвиг подъема оси на 10мм влево по Z": "G91\nG1 Z-10 F3000\n",
                        "Сдвиг подъема оси на 10мм вправо по Z": "G91\nG1 Z10 F3000\n"
                    }
                    if command_text in commands:
                        ser.write(commands[command_text].encode())
                    return Response({"message": f"Команда '{command_text}' успешно отправлена на принтер."}, status=status.HTTP_200_OK)
            except serial.SerialException as e:
                logger.error(f"Error controlling printer: {e}")
                return Response({"error": f"Ошибка: {e}"}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
        return Response({"error": "Не указана команда"}, status=status.HTTP_400_BAD_REQUEST)

@admin_required
def select_printer(request):
    printers = ThreeDPrinterUser.objects.all()
    if request.method == 'POST':
        printer_id = request.POST.get('printer_id')
        printer = get_object_or_404(ThreeDPrinterUser, id=printer_id)
        printer.delete()
        return redirect('printers_list')
    return render(request, 'select_printer.html', {'printers': printers})

@admin_required
def send_command(request, printer_id):
    selected_printer = get_object_or_404(ThreeDPrinter, id=printer_id)
    if request.method == 'POST':
        command = request.POST.get('command')
        try:
            with serial.Serial(selected_printer.com_port, 115200, timeout=1) as ser:
                ser.write(command.encode())
                return HttpResponse(f"Command '{command}' sent to printer {selected_printer.name}.")
        except serial.SerialException as e:
            logger.error(f"Error sending command to printer: {e}")
            return HttpResponse(f"Error: {e}")
    return render(request, 'send_command.html', {'selected_printer': selected_printer})

@admin_required
def printer_info(request, printer_id):
    selected_printer = get_object_or_404(ThreeDPrinter, id=printer_id)
    return render(request, 'printer_info.html', {'selected_printer': selected_printer})

@admin_required
def delete_printer(request, printer_id):
    try:
        printer = get_object_or_404(ThreeDPrinter, pk=printer_id)
        printer.delete()
        return redirect('select_printer')
    except ThreeDPrinter.DoesNotExist:
        return render(request, 'select_printer.html', {'printer_id': printer_id})

def home(request):
    return render(request, 'web.html')

def print_order(request):
    if request.method == 'POST':
        order_id = request.POST.get('order_id')
        success = True
        return JsonResponse({'success': success})
    else:
        return JsonResponse({'success': False, 'error': 'Invalid request method'})

@login_required
def update_order(request, order_id):
    if request.method == 'POST':
        price = request.POST.get('price')
        status = request.POST.get('status')
        order = get_object_or_404(Order, pk=order_id)

printer/templates/add_printer.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
    <title>Добавление принтера</title>
 <style>
    button {
    display: block;
    margin: auto;
    padding: 10px 20px;
    background-color: #4CAF50;
    color: white;
    border: none;
    border-radius: 5px;
    cursor: pointer;
}


</style>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        .header {
            background-color: #333;
            color: #fff;
            padding: 10px 20px;
            display: flex;
            align-items: center;
            justify-content: space-between;
        }

        .logo {
            font-size: 24px;
            font-weight: bold;
            text-decoration: none;
            color: #fff;
        }

        .nav {
            display: flex;
            align-items: center;
        }

        .nav-item {
            margin-right: 20px;
            font-size: 18px;
        }

        .user-info {
            display: flex;
            align-items: center;
            color: #ccc;
        }

        .user-info span {
            margin-right: 10px;
        }

        .logout-button {
            background-color: #007BFF;
            color: white;
            border: none;
            border-radius: 5px;
            padding: 8px 16px;
            cursor: pointer;
        }

        .logout-button:hover {
            background-color: #0056b3;
        }

        h2 {
            color: #333;
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-top: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th, td {
            border: 2px solid #ddd;
            padding: 15px;
            text-align: center;
            font-size: 21px; /* Set text size to 21px */
        }

        th {
            background-color: #f2f2f2;
        }

        button {
            padding: 10px;
            cursor: pointer;
            border: none;
            border-radius: 10px;
            font-size: 16px; /* Set button text size */
            background-color: #4CAF50;
            color: white;
            margin-top: 10px;
        }

        button:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
<header class="header">
        <a href="#" class="logo">Добавление принтера</a>
        <nav class="nav">
             <button onclick="window.location.href='{% url 'web' %}'">Главная</button>
            <button onclick="window.location.href='{% url 'select_printer' %}'">Принтеры</button>
            <button onclick="window.location.href='{% url 'orders' %}'">Заказы</button>

        </nav>
        <div class="user-info">
            <li><a href="#">ID: {{ user.username }}</a></li>
               <li> <a href="{% url 'users:logout' %}?next={% url 'web' %}" class="logout-button">Выход</a></li>
        </div>
    </header>


  <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Добавить</button>
  </form>

</body>
</html>

printer/templates/base.html
{% load static %}
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>3d-печать</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">

</head>
<body>
<header>
    {% block header %}
    <header class="site-header">
        <div class="site-identity">
            <h1><a href="#">3d</a></h1>
        </div>
        <nav class="site-navigation">
            <ul class="nav">
                <li><a href="/control_printer">О нас</a></li>
                <li><a href="/add_3d_printer">Галерея</a></li>
                <li><a href="/print">Печать</a></li>
                <li><a href="#" data-toggle="modal" data-target="#loginModal">Вход</a></li>
            </ul>
        </nav>
    </header>

    <div class="modal" id="loginModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Вход</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <div class="modal-body">
                    <form method="post" action="{% url 'users:login_user' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_username">Имя пользователя:</label>
                            <input type="text" name="username" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="id_password">Пароль:</label>
                            <input type="password" name="password" class="form-control" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Войти</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}
</header>


</body>
</html>

printer/templates/header.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>3d-печать</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">
</head>
<header class="site-header">
    <div class="site-identity">
        <h1><a href="{% url 'web' %}">3d</a></h1>
    </div>
    <nav class="site-navigation">
        <ul class="nav">
            {% if user.is_authenticated %}
                {% if user.is_staff %}
                    <li><a href="{% url 'select_printer' %}">Личный кабинет админа</a></li>
                    <li><a href="{% url 'management' %}">Личный кабинет</a></li>
                {% else %}
                    <li><a href="{% url 'management' %}">Личный кабинет</a></li>
                {% endif %}
                <li><a href="#">ID: {{ user.username }}</a></li>
                <li><a href="{% url 'users:logout' %}?next={% url 'web' %}" class="logout-button">Выход</a></li>
            {% else %}
                <li><a href="#" data-toggle="modal" data-target="#loginModal">Вход</a></li>
                <li><a href="{% url 'users:register' %}">Регистрация</a></li>
            {% endif %}
        </ul>
    </nav>
    <!-- Модальное окно для входа -->
    <div class="modal" id="loginModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Вход</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form method="post" action="{% url 'users:login_user' %}">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_username">Имя пользователя:</label>
                            <input type="text" name="username" class="form-control" required>
                        </div>
                        <div class="form-group">
                            <label for="id_password">Пароль:</label>
                            <input type="password" name="password" class="form-control" required>
                        </div>
                        <button type="submit" class="btn btn-primary">Войти</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</header>

printer/templates/kab_print.html
{% load static %}
{% include 'header.html' %}

<html lang="en">
<head>

    <link rel="stylesheet" type="text/css" href="{% static 'css/print.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css">
</head>
<body>
<div class="wrapper">
    <div class="sidebar">
        <div class="tab">
            <a href="{% url 'printers_user' %}" class="tablinks">Принтеры</a>
            <a href="{% url 'orders_user' %}" class="tablinks">Заказы</a>
            <a href="{% url 'management' %}" class="tablinks">Управление</a>
            <a href="{% url 'printing' %}" class="tablinks">Печать и моделирование</a>
        </div>
    </div>
    <div class="content">
        {% block content %}{% endblock %}
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.3.1.js"
                integrity="sha256-2Kc2pTH7YXmjUpdilW5fukfR9GhYxyoto0+U1oD5swE="
                crossorigin="anonymous"></script>
            <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.js"></script>
</body>
</html>

printer/templates/print_gcode.html
{% include 'header.html' %}
{% load static %}

<html lang="en">
<head>
    <style>
    button {
    display: block;
    margin: auto;
    padding: 10px 20px;
    background-color: #4CAF50; /* Green background color */
    color: white; /* White text color */
    border: none; /* Remove borders */
    border-radius: 5px; /* Optional: Add rounded corners */
    cursor: pointer; /* Add a pointer cursor on hover */
}

button:hover {
    background-color: #45a049; /* Darker green on hover */
}</style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Печать</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/form.css' %}">
</head>
<body>

<form method="post" enctype="multipart/form-data" action="{% url 'printer:print_gcode' %}">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Upload GCode</button>
</form>

<!-- Add the button to go back to the home page -->
<a href="{% url 'printerapp:web' %}"><button>На главную страницу</button></a>

</body>
</html>

printer/templates/web.html
{% load static %}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>3D-печать</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}">

    <style>
        body {
            font-family: 'Arial', sans-serif;
            background-color: #f4f4f9;
            color: #333;
        }

        #about-us {
            background-color: #fff;
            padding: 50px 0;
        }

        #about-us h2 {
            font-size: 36px;
            font-weight: bold;
            margin-bottom: 30px;
        }

        #about-us p {
            font-size: 18px;
            line-height: 1.6;
        }

        #gallery {
            padding: 50px 0;
        }

        #gallery h2 {
            font-size: 36px;
            font-weight: bold;
            margin-bottom: 30px;
        }

        #gallery .img-fluid {
            -webkit-transition: 0.3s ease;
            transition: 0.3s ease;
        }

        #gallery .img-fluid:hover {
            -webkit-transform: scale(1.1);
            transform: scale(1.1);
        }

        .hero-section {
            background-image: url("{% static 'img/back_image1.png' %}");
            background-size: cover;
            background-position: center;
            padding: 100px 0;
        }

        .hero-section h2 {
            font-size: 42px;
            color: #fff;
        }

        .hero-section p {
            font-size: 20px;
            color: #fff;
        }

        #map {
            padding: 50px 0;
        }
    </style>
</head>
<body>
    {% include 'header.html' %}

    <section class="hero-section text-center text-white d-flex align-items-center">
        <div class="container">
            <h2 class="display-4">Добро пожаловать в мир 3D-печати</h2>
            <p class="lead">Мы воплотим ваши идеи в реальность!</p>
            <a href="#about-us" class="btn btn-primary mt-3">Узнать больше</a>
        </div>
    </section>

    <section id="about-us">
        <div class="container text-center">
            <h2>О нас</h2>
            <p>Добро пожаловать на наш веб-сайт! Мы занимаемся 3D-печатью и стремимся предоставить вам высококачественные услуги. Наша команда профессионалов готова воплотить ваши идеи в реальность с использованием современных технологий 3D-печати.</p>
            <p>Инновации, качество и удовлетворенность клиентов - вот что делает нас лучшими в этой области. Мы стремимся к тому, чтобы каждый проект был уникальным и соответствовал вашим ожиданиям.</p>
        </div>
    </section>

    <section id="gallery" class="container-fluid">
        <div class="container text-center">
            <h2>Наши проекты</h2>
        </div>
        <div class="row mt-4 text-center">
            <div class="col-md-3 mb-4">
                <img src="{% static 'img/image1.jpeg' %}" alt="Изображение 1" class="img-fluid">
            </div>
            <div class="col-md-3 mb-4">
                <img src="{% static 'img/image2.jpg' %}" alt="Изображение 2" class="img-fluid">
            </div>
            <div class="col-md-3 mb-4">
                <img src="{% static 'img/image3.jpeg' %}" alt="Изображение 3" class="img-fluid">
            </div>
            <div class="col-md-3 mb-4">
                <img src="{% static 'img/image4.jpg' %}" alt="Изображение 4" class="img-fluid">
            </div>
        </div>
    </section>

    <section class="hero-section">
        <div class="container">


<div class="row justify-content-end">
                <div class="col-12 col-md-6 col-xl-5 text-white">
                    <div class="p-4 bg-dark rounded">
                        <h2 class="mb-4"><strong>Предлагаем возможность сдачи принтера в аренду</strong></h2>
                        <p class="lead">Также у нас на сайте вы можете сдать свой принтер нам в удаленную аренду, чтобы вы могли заработать на печати.</p>
                        <a href="{% url 'users:register' %}" class="btn btn-outline-light mt-3">Зарегистрироваться</a>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="map" class="text-center">
        <div class="container">
            <h2>Как нас найти</h2>
            <div class="mt-4" style="width: 100%; height: 400px;">
                <script type="text/javascript" charset="utf-8" src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3A053bd947d462cc1a45aeba4070defff75501905071c0eaf68436ac9976ec698c&amp;width=100%&amp;height=400&amp;lang=ru_RU&amp;apikey=<API-ключ>"></script>
            </div>
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>